export const CHANGE_INGRIDIENTS = 'CHANGE_INGRIDIENTS';
export const CHANGE_TOTAL_PRICE = 'CHANGE_TOTAL_PRICE';

export const ORDER_SUBMIT = 'ORDER_SUBMIT';
export const ORDER_SUBMIT_SUCCESS = 'ORDER_SUBMIT_SUCCESS';
export const ORDER_SUBMIT_FAIL = 'ORDER_SUBMIT_FAIL';
export const ORDER_SUBMIT_START = 'ORDER_SUBMIT_START';